# These rules will change if you change your site’s custom domains or HTTPS settings
# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://serene-joliot-d9cc1d.netlify.com/*"
  to = "https://blog.benkitv.com/:splat"
  status = 301
  force = true
